apiVersion: v1
kind: Service
metadata:
  labels:
    app: feed_microservice
  name: feed_microservice-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/feed_microservice-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: feed_microservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
